spring.application.name=DistilledRecords

server.port=8081
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.username=admin
spring.datasource.password=rootbd2
spring.datasource.url=jdbc:mysql://192.168.56.101:3306/licorera

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.data.mongodb.url=mongodb://127.0.0.1:27017/distilled_records_nosql
