DROP DATABASE IF EXISTS LICORERA;

CREATE DATABASE LICORERA;

USE LICORERA;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS DETALLE_VENTA;
DROP TABLE IF EXISTS VENTA;
DROP TABLE IF EXISTS PRODUCTO;
DROP TABLE IF EXISTS INVENTARIO;
DROP TABLE IF EXISTS CATEGORIA;
DROP TABLE IF EXISTS PROVEEDOR;
DROP TABLE IF EXISTS EMPLEADO;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS CIUDAD;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE CIUDAD (
  ID_CIUDAD INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE VARCHAR(60) NOT NULL UNIQUE
);

CREATE TABLE USUARIO (
  ID_USUARIO VARCHAR(50) PRIMARY KEY,
  NOMBRE VARCHAR(60) NOT NULL,
  NUM_TELEFONO VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE CLIENTE (
  ID_CLIENTE VARCHAR(15) PRIMARY KEY,
  ID_USUARIO VARCHAR(50) NOT NULL UNIQUE,    
  CORREO VARCHAR(120) NOT NULL UNIQUE,

  CONSTRAINT fk_cliente_usuario
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE EMPLEADO (
  ID_EMPLEADO VARCHAR(15) PRIMARY KEY,
  ID_USUARIO VARCHAR(50) NOT NULL UNIQUE,       
  USER_NAME VARCHAR(50) NOT NULL UNIQUE,

  CONSTRAINT fk_empleado_usuario
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE PROVEEDOR (
  ID_PROVEEDOR VARCHAR(15) PRIMARY KEY,
  ID_USUARIO VARCHAR(50) NOT NULL UNIQUE,    
  CORREO VARCHAR(120) NOT NULL UNIQUE,
  DIRECCION VARCHAR(200) NOT NULL,
  ID_CIUDAD INT NOT NULL,
  CONSTRAINT fk_proveedor_usuario
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
  CONSTRAINT fk_proveedor_ciudad
    FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD)
);

CREATE TABLE CATEGORIA (
    ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100),
    DESCRIPCION VARCHAR(200)
);

CREATE TABLE INVENTARIO (
    ID_INVENTARIO INT AUTO_INCREMENT PRIMARY KEY,
    CANTIDAD_DISPONIBLE INT
);

CREATE TABLE PRODUCTO (
    ID_PRODUCTO INT AUTO_INCREMENT PRIMARY KEY,
    MARCA VARCHAR(100),
    PRECIO INT,
    GRADO_ALCOHOL INT,
    ID_PROVEEDOR VARCHAR(15),
    ID_CATEGORIA INT,
    ID_INVENTARIO INT,
    CONSTRAINT FK_PRODUCTO_PROVEEDOR 
        FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR),
    CONSTRAINT FK_PRODUCTO_CATEGORIA 
        FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA),
    CONSTRAINT FK_PRODUCTO_INVENTARIO 
        FOREIGN KEY (ID_INVENTARIO) REFERENCES INVENTARIO(ID_INVENTARIO)
);

CREATE TABLE VENTA (
    ID_VENTA INT AUTO_INCREMENT PRIMARY KEY,
    MONTO DECIMAL(10,2),
    FECHA DATE,
    ID_CLIENTE VARCHAR(15),
    ID_EMPLEADO VARCHAR(15),
    CONSTRAINT FK_VENTA_CLIENTE 
        FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_VENTA_EMPLEADO 
        FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO)
);

CREATE TABLE DETALLE_VENTA (
    ID_DETALLE INT AUTO_INCREMENT PRIMARY KEY,
    CANTIDAD_PRODUCTOS INT,
    SUBTOTAL DECIMAL(10,2),
    IVA DECIMAL(10,2),
    ID_VENTA INT,
    ID_PRODUCTO INT,
    CONSTRAINT FK_DETALLE_VENTA_VENTA 
        FOREIGN KEY (ID_VENTA) REFERENCES VENTA(ID_VENTA),
    CONSTRAINT FK_DETALLE_VENTA_PRODUCTO 
        FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);